# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poslog < Formula
  desc "Parser to extract SQL from postgresql.log"
  homepage "https://github.com/winebarrel/poslog"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/poslog/releases/download/v0.3.3/poslog_0.3.3_darwin_amd64.tar.gz"
      sha256 "179f9f1fc7e51a5ef92f5728f9d686f66bad1182523c0b6823ee21dc9e4c38ec"

      def install
        bin.install 'poslog'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/poslog/releases/download/v0.3.3/poslog_0.3.3_darwin_arm64.tar.gz"
      sha256 "5c01dd406fa9be3876439b58ccdc7420842e3eaff0f5f0670812fff2d3534fc4"

      def install
        bin.install 'poslog'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/poslog/releases/download/v0.3.3/poslog_0.3.3_linux_amd64.tar.gz"
      sha256 "b56aba7331651071f5781092dabb45347e125b6b55948201750fdf9f65f42a14"

      def install
        bin.install 'poslog'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/poslog/releases/download/v0.3.3/poslog_0.3.3_linux_arm64.tar.gz"
      sha256 "67f8c61bd0a77cf77effed92906e96c636a8fffd781557e424a2db1946655727"

      def install
        bin.install 'poslog'
      end
    end
  end
end
