# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poslog < Formula
  desc "Parser to extract SQL from postgresql.log"
  homepage "https://github.com/winebarrel/poslog"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/poslog/releases/download/v0.2.1/poslog_0.2.1_darwin_amd64.tar.gz"
      sha256 "30c9ef71cc0c433650360fcd7d9720db24a4396167ee21dd87d1a6e186b6dc40"

      def install
        bin.install 'poslog'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/poslog/releases/download/v0.2.1/poslog_0.2.1_darwin_arm64.tar.gz"
      sha256 "ab0af047cd47f4b6ac63e7a65e4ff7824c36fc8360e45e92afce54ca28ed5e5b"

      def install
        bin.install 'poslog'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/poslog/releases/download/v0.2.1/poslog_0.2.1_linux_arm64.tar.gz"
      sha256 "51105eab419075b4c8e0d9db33a63ec7fe076399b44c41157b70be88a6d40c13"

      def install
        bin.install 'poslog'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/poslog/releases/download/v0.2.1/poslog_0.2.1_linux_amd64.tar.gz"
      sha256 "0e3c17fbdbbea4b91a16c37dd65fdc8774a554303b00f78cfe763b3467c1e3b6"

      def install
        bin.install 'poslog'
      end
    end
  end
end
