# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poslog < Formula
  desc "Parser to extract SQL from postgresql.log"
  homepage "https://github.com/winebarrel/poslog"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/poslog/releases/download/v0.5.1/poslog_0.5.1_darwin_arm64.tar.gz"
      sha256 "2ea7dbe6b7f9b9eb8bb7cfa6ea7366ead2d014cb1eb1462e2e941a9d0d669bab"

      def install
        bin.install 'poslog'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/poslog/releases/download/v0.5.1/poslog_0.5.1_darwin_amd64.tar.gz"
      sha256 "6be2ba1f73e9f4e7da7cc5e2888f62ece49a5966087ee62e4ad527641c1229a2"

      def install
        bin.install 'poslog'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/poslog/releases/download/v0.5.1/poslog_0.5.1_linux_amd64.tar.gz"
      sha256 "b388c5cf56183cd1293a5d149b05ef4fa730c5925d338e41272a3e6a998d0f58"

      def install
        bin.install 'poslog'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/poslog/releases/download/v0.5.1/poslog_0.5.1_linux_arm64.tar.gz"
      sha256 "ba49adc87ea6bddba9e777d253a35593055eec9d7fb501a1d3c48e19e21490f8"

      def install
        bin.install 'poslog'
      end
    end
  end
end
